<?php

$name = 'Alex';
$age = 22;
define('PI', 3.14);
echo $name;
echo '<br>';
echo $age;
echo '<br>';
echo PI;
echo '<hr>';
$str1 = 'Jack is a good student';
$str2 = ' who is always on time to school';
$combine = $str1;
$combine .= $str2;
echo 'Full string is: ' . $combine;
echo '<br>';
echo 'First letter upper: ' . ucfirst($combine);
echo '<br>';
echo 'First letters upper: ' . ucwords($combine);
echo '<br>';
echo 'All to upper: ' . strtoupper($combine);
echo '<br>';
echo 'All to lower: ' . strtolower($combine);
echo '<br>';
echo 'Substr: ' . substr($combine, 5, 15);
echo '<br>';
echo 'Repeat: ' . str_repeat($combine, 5);
echo '<br>';
echo 'Position: ' . strpos($combine, 'go');
echo '<br>';
echo 'Char: ' . strchr($combine, 't');
echo '<br>';
echo 'Length: ' . strlen($combine);
echo '<br>';
echo 'Trim: ' . trim($combine);
echo '<br>';
echo 'After a word: ' . strstr($combine, 'student');
echo '<br>';
echo 'Replace: ' . str_replace('is', 'are', $combine);
echo '<br>';
